server:
  port: 1777
spring:
  application:
    name: publisher
  rabbitmq:
    host: 123.249.19.24
    port: 5672
    username: windy
    password: windy
    #添加虚拟主机
    virtual-host: /
    #开启publish-return功能，同样是基于callback机制，不过是定义ReturnCallback
    publisher-returns: false
    #开启publisher-confirm simple：同步等待confirm结果，直到超时 correlated：异步回调，定义ConfirmCallback，MQ返回结果时会回调这个ConfirmCallback
    publisher-confirm-type: none
    template:
      retry:
        enabled: true #开启超时重试机制，默认为false
        initial-interval: 1000ms #失败后的初始等待时间
        multiplier: 1 #失败后下次等待的时长倍数，下次等待时长= initial-interval*multiplier
        max-attempts: 2 #最大重试次数，默认是3次
      mandatory: true #定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
    connection-timeout: 200ms #设置连接MQ超时时间


