server:
  port: 1666
spring:
  application:
    name: consumer
  rabbitmq:
    host: 123.249.19.24
    port: 5672
    username: windy
    password: windy
    #添加虚拟主机
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 消费者预取的消息数量，每次只能获取1条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto # 手动ack，当消费者接收到信息后，queue队列里消息不会消失。默认为auto
        #        acknowledge-mode: manual # 手动ack，当消费者接收到信息后，queue队列里消息不会消失。默认为auto
        retry:
          enabled: true #开启消费者失败重试
          initial-interval: 1000ms #初始失败等待时长为1s
          multiplier: 1 #下次失败的等待时长倍数 下次等待时长= initial-interval* multiplier
          max-attempts: 3 #最大重试次数，默认是3
          #true 无状态；false 有状态 如果业务中包含事务，这里为false 如果为false的话，实际重试的次数为2 失败后消息会返回MQ
          stateless: true